server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  data:
    cassandra:
      keyspace-name: springcloud
      contact-points: localhost
      port: 9042
      schema:
        action: NONE

      username: cassandra
      password: cassandra