spring:
  data:
    cassandra:
      keyspace-name: springcloud
      contact:
        points: localhost
      port: 9042
      schema:
        action: NONE
      username: cassandra
      password: cassandra