spring:
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    username: admin
    password: admin
    port: 15672
    host: localhost
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey

  main:
    allow-circular-references: true
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/carddb
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/:
