server:
  port: 8503

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: notification-service
  rabbitmq:
    username: admin
    password: admin
    port: 15672
    host: localhost
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey

