version: '3.9'
services:
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
